spring:
  application:
    name: ecsfgex
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      mode: "full"
  # prometheusのmetrics出力にapplication識別用のタグを追加する
  metrics:
    tags:
      application: "ecsfgex"

ecsfgex:
  contents: "ecsfgex default text on application.yml !!"
