name: docker test

on: workflow_dispatch

jobs:
  dockertest:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
